import type { PackDataDTO } from '@/shared/types/pack';

export const packs: PackDataDTO[] = [
  {
    packDisplayNameZH: '宏愿兵装组合包',
    packDisplayNameEN: '宏愿兵装组合包',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/宏愿兵装组合包.png',
    contents: [
      {
        itemId: '宏愿',
        itemName: '宏愿',
        quantity: 1,
      },
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 6,
      },
    ],
  },
  {
    packDisplayNameZH: '全面人才组合包',
    packDisplayNameEN: '全面人才组合包',
    price: 128,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/全面人才组合包.png',
    contents: [
      {
        itemId: '特许寻访凭证',
        itemName: '特许寻访凭证',
        quantity: 10,
      },
      {
        itemId: '武库配额',
        itemName: '武库配额',
        quantity: 2000,
      },
    ],
  },
  {
    packDisplayNameZH: '人事支援组合包',
    packDisplayNameEN: '人事支援组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/人事支援组合包.png',
    contents: [
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantity: 10,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantity: 100000,
      },
    ],
  },
  {
    packDisplayNameZH: '协议源流组合包',
    packDisplayNameEN: '协议源流组合包',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/协议源流组合包.png',
    contents: [
      {
        itemId: '特许寻访凭证',
        itemName: '特许寻访凭证',
        quantity: 10,
      },
      {
        itemId: '武库配额',
        itemName: '武库配额',
        quantity: 2000,
      },
      {
        itemId: '存续的痕迹',
        itemName: '存续的痕迹',
        quantity: 10,
      },
    ],
  },
  {
    packDisplayNameZH: '行火寻访组合包',
    packDisplayNameEN: '行火寻访组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/行火寻访组合包.png',
    contents: [
      {
        itemId: '行火留烬十连凭证',
        itemName: '行火留烬十连凭证',
        quantity: 1,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantity: 80000,
      },
    ],
  },
  {
    packDisplayNameZH: '每月素材组合包',
    packDisplayNameEN: '每月素材组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/每月素材组合包.png',
    contents: [
      {
        itemId: '折金票',
        itemName: '折金票',
        quantity: 100000,
      },
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantity: 10,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantity: 25,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantity: 20,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantity: 20,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantity: 50,
      },
      {
        itemId: '高阶培养自选箱I',
        itemName: '高阶培养自选箱I',
        quantity: 20,
      },
    ],
  },
  {
    packDisplayNameZH: '每周素材组合包',
    packDisplayNameEN: '每周素材组合包',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/每周素材组合包.png',
    contents: [
      {
        itemId: '折金票',
        itemName: '折金票',
        quantity: 30000,
      },
      {
        itemId: '初级认知载体',
        itemName: '初级认知载体',
        quantity: 120,
      },
      {
        itemId: '武器检查装置',
        itemName: '武器检查装置',
        quantity: 240,
      },
    ],
  },
  {
    packDisplayNameZH: '特惠武库配额包',
    packDisplayNameEN: '特惠武库配额包',
    price: 88,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/特惠武库配额包.png',
    contents: [
      {
        itemId: '武库配额',
        itemName: '武库配额',
        quantity: 2000,
      },
    ],
  },
  {
    packDisplayNameZH: '优惠武库配额包',
    packDisplayNameEN: '优惠武库配额包',
    price: 108,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/优惠武库配额包.png',
    contents: [
      {
        itemId: '武库配额',
        itemName: '武库配额',
        quantity: 2000,
      },
    ],
  },
  {
    packDisplayNameZH: '标准武库配额包',
    packDisplayNameEN: '标准武库配额包',
    price: 128,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/标准武库配额包.png',
    contents: [
      {
        itemId: '武库配额',
        itemName: '武库配额',
        quantity: 2000,
      },
    ],
  },
  {
    packDisplayNameZH: '月卡',
    packDisplayNameEN: '月卡',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/月卡.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 12,
      },
      {
        itemId: '嵌晶玉',
        itemName: '嵌晶玉',
        quantity: 6000,
      },
      {
        itemId: '应急理智加强剂',
        itemName: '应急理智加强剂',
        quantity: 30,
      },
    ],
  },
  {
    packDisplayNameZH: '6元双倍源石',
    packDisplayNameEN: '6元双倍源石',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/6元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 6,
      },
    ],
  },
  {
    packDisplayNameZH: '30元双倍源石',
    packDisplayNameEN: '30元双倍源石',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/30元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 24,
      },
    ],
  },
  {
    packDisplayNameZH: '98元双倍源石',
    packDisplayNameEN: '98元双倍源石',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/98元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 84,
      },
    ],
  },
  {
    packDisplayNameZH: '198元双倍源石',
    packDisplayNameEN: '198元双倍源石',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/198元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 170,
      },
    ],
  },
  {
    packDisplayNameZH: '328元双倍源石',
    packDisplayNameEN: '328元双倍源石',
    price: 328,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/328元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 282,
      },
    ],
  },
  {
    packDisplayNameZH: '648元双倍源石',
    packDisplayNameEN: '648元双倍源石',
    price: 648,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/648元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 560,
      },
    ],
  },
  {
    packDisplayNameZH: '6元源石',
    packDisplayNameEN: '6元源石',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/6元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 3,
      },
    ],
  },
  {
    packDisplayNameZH: '30元源石',
    packDisplayNameEN: '30元源石',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/30元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 15,
      },
    ],
  },
  {
    packDisplayNameZH: '98元源石',
    packDisplayNameEN: '98元源石',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/98元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 50,
      },
    ],
  },
  {
    packDisplayNameZH: '198元源石',
    packDisplayNameEN: '198元源石',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/198元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 102,
      },
    ],
  },
  {
    packDisplayNameZH: '328元源石',
    packDisplayNameEN: '328元源石',
    price: 328,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/328元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 171,
      },
    ],
  },
  {
    packDisplayNameZH: '648元源石',
    packDisplayNameEN: '648元源石',
    price: 648,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/648元源石.png',
    contents: [
      {
        itemId: '衍质源石',
        itemName: '衍质源石',
        quantity: 350,
      },
    ],
  },
  {
    packDisplayNameZH: '协议定制',
    packDisplayNameEN: '协议定制',
    price: 68,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/协议定制.png',
    contents: [
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 20 },
      { itemId: '海盐冰淇淋', itemName: '海盐冰淇淋', quantity: 1 },
      { itemId: '中级作战记录', itemName: '中级作战记录', quantity: 50 },
      { itemId: '武器检查装置', itemName: '武器检查装置', quantity: 50 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 8 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 2 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '启程', itemName: '启程', quantity: 1 }, // 头像
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 2 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '多用进阶自选箱', itemName: '多用进阶自选箱', quantity: 2 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '启程', itemName: '启程', quantity: 1 }, // 头像框
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 3 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '技能提升自选箱', itemName: '技能提升自选箱', quantity: 3 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '武器补给·唤醒', itemName: '武器补给·唤醒', quantity: 1 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 2 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '理智萃取器', itemName: '理智萃取器', quantity: 5 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '武库配额', itemName: '武库配额', quantity: 800 },
      { itemId: '草莓可丽饼', itemName: '草莓可丽饼', quantity: 1 },
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 5 },
      { itemId: '多用进阶自选箱', itemName: '多用进阶自选箱', quantity: 5 },
      { itemId: '折金票', itemName: '折金票', quantity: 50000 },
      { itemId: '协议化武器原型', itemName: '协议化武器原型', quantity: 1 },
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 8 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 20 },
      { itemId: '技能提升自选箱', itemName: '技能提升自选箱', quantity: 8 },
      { itemId: '折金票', itemName: '折金票', quantity: 65000 },
      { itemId: '启程', itemName: '启程', quantity: 1 }, // 名片主题
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 4 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 20 },
      { itemId: '理智萃取器', itemName: '理智萃取器', quantity: 5 },
      { itemId: '折金票', itemName: '折金票', quantity: 65000 },
      { itemId: '协议化武器原型', itemName: '协议化武器原型', quantity: 1 },
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 8 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 30 },
      { itemId: '高阶培养自选箱I', itemName: '高阶培养自选箱I', quantity: 8 },
      { itemId: '折金票', itemName: '折金票', quantity: 80000 },
      { itemId: '武库配额', itemName: '武库配额', quantity: 800 },
      { itemId: '栗花蜜', itemName: '栗花蜜', quantity: 1 },
      { itemId: '技能提升自选箱', itemName: '技能提升自选箱', quantity: 6 },
      { itemId: '高阶培养自选箱I', itemName: '高阶培养自选箱I', quantity: 6 },
      { itemId: '折金票', itemName: '折金票', quantity: 80000 },
      { itemId: '存续的痕迹', itemName: '存续的痕迹', quantity: 10 },
      { itemId: '多用经验自选箱', itemName: '多用经验自选箱', quantity: 10 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 30 },
      { itemId: '高阶培养自选箱I', itemName: '高阶培养自选箱I', quantity: 10 },
      { itemId: '折金票', itemName: '折金票', quantity: 100000 },
      { itemId: '武库配额', itemName: '武库配额', quantity: 800 },
      { itemId: '技能提升自选箱', itemName: '技能提升自选箱', quantity: 10 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 30 },
      { itemId: '高阶培养自选箱I', itemName: '高阶培养自选箱I', quantity: 10 },
      { itemId: '折金票', itemName: '折金票', quantity: 100000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 8 },
    ],
  },
  {
    packDisplayNameZH: '源石配给',
    packDisplayNameEN: '源石配给',
    descriptionZH: '价格为源石折算',
    descriptionEN: '价格为源石折算',
    price: Math.round((29 / 350) * 648 * 10) / 10,
    imageUrl: 'https://cos.yituliu.cn/endfield/pack-image/源石配给.png',
    contents: [
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: '中级作战记录', itemName: '中级作战记录', quantity: 30 },
      { itemId: '武器检查装置', itemName: '武器检查装置', quantity: 30 },
      { itemId: '折金票', itemName: '折金票', quantity: 15000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 5 },
      { itemId: '中级作战记录', itemName: '中级作战记录', quantity: 30 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 5 },
      { itemId: '武器检查装置', itemName: '武器检查装置', quantity: 30 },
      { itemId: '折金票', itemName: '折金票', quantity: 15000 },
      { itemId: '贴纸·记忆', itemName: '贴纸·记忆', quantity: 1 },
      { itemId: '协议圆盘', itemName: '协议圆盘', quantity: 15 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 5 },
      { itemId: '强固模具', itemName: '强固模具', quantity: 15 },
      { itemId: '折金票', itemName: '折金票', quantity: 15000 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 2 },
      { itemId: '高级作战记录', itemName: '高级作战记录', quantity: 10 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 5 },
      { itemId: '武器检查套组', itemName: '武器检查套组', quantity: 10 },
      { itemId: '折金票', itemName: '折金票', quantity: 20000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 5 },
      { itemId: '协议棱柱', itemName: '协议棱柱', quantity: 50 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 5 },
      { itemId: '协议棱柱', itemName: '协议棱柱', quantity: 50 },
      { itemId: '折金票', itemName: '折金票', quantity: 20000 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 3 },
      { itemId: '高级认知载体', itemName: '高级认知载体', quantity: 8 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: '武器检查套组', itemName: '武器检查套组', quantity: 20 },
      { itemId: '折金票', itemName: '折金票', quantity: 30000 },
      { itemId: '滤镜·黑金', itemName: '滤镜·黑金', quantity: 1 },
      { itemId: '协议圆盘组', itemName: '协议圆盘组', quantity: 10 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '重型强固模具', itemName: '重型强固模具', quantity: 10 },
      { itemId: '折金票', itemName: '折金票', quantity: 40000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 5 },
      { itemId: '协议棱柱组', itemName: '协议棱柱组', quantity: 20 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 10 },
      { itemId: '协议棱柱组', itemName: '协议棱柱组', quantity: 20 },
      { itemId: '折金票', itemName: '折金票', quantity: 40000 },
      { itemId: '武器补给·唤醒', itemName: '武器补给·唤醒', quantity: 1 },
      { itemId: '高级认知载体', itemName: '高级认知载体', quantity: 10 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 15 },
      { itemId: '武器检查套组', itemName: '武器检查套组', quantity: 25 },
      { itemId: '折金票', itemName: '折金票', quantity: 50000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 5 },
      { itemId: '协议圆盘组', itemName: '协议圆盘组', quantity: 20 },
      { itemId: '应急理智加强剂', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: '重型强固模具', itemName: '重型强固模具', quantity: 20 },
      { itemId: '折金票', itemName: '折金票', quantity: 50000 },
      { itemId: '存续的痕迹', itemName: '存续的痕迹', quantity: 6 },
      { itemId: '协议棱柱组', itemName: '协议棱柱组', quantity: 30 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 15 },
      { itemId: '协议棱柱组', itemName: '协议棱柱组', quantity: 30 },
      { itemId: '折金票', itemName: '折金票', quantity: 60000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 5 },
      { itemId: '高级认知载体', itemName: '高级认知载体', quantity: 12 },
      { itemId: '理智消耗许可', itemName: '理智消耗许可', quantity: 15 },
      { itemId: '武器检查套组', itemName: '武器检查套组', quantity: 30 },
      { itemId: '折金票', itemName: '折金票', quantity: 60000 },
      { itemId: '衍质源石', itemName: '衍质源石', quantity: 7 },
    ],
  },
];
