import type { Packs } from '@/shared/types/pack';

export const packs: Packs = {
  newbie_giftpack_6_special: {
    packId: 'newbie_giftpack_6_special',
    packDisplayNameZH: '宏愿兵装组合包',
    packDisplayNameEN: '宏愿兵装组合包',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/宏愿兵装组合包.webp',
    contents: [
      { itemId: 'wpn_sword_0021', itemName: '宏愿', quantity: 1 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 6 },
    ],
  },
  newbie_giftpack_01: {
    packId: 'newbie_giftpack_01',
    packDisplayNameZH: '全面人才组合包',
    packDisplayNameEN: '全面人才组合包',
    price: 128,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/全面人才组合包.webp',
    contents: [
      { itemId: 'item_ticketgacha_special_single', itemName: '特许寻访凭证', quantity: 10 },
      { itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 2000 },
    ],
  },
  newbie_giftpack_02: {
    packId: 'newbie_giftpack_02',
    packDisplayNameZH: '人事支援组合包',
    packDisplayNameEN: '人事支援组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/人事支援组合包.webp',
    contents: [
      { itemId: 'item_ticketgacha_standard_single', itemName: '基础寻访凭证', quantity: 10 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 100_000 },
    ],
  },
  seasonal_giftpack_combine: {
    packId: 'seasonal_giftpack_combine',
    packDisplayNameZH: '协议源流组合包',
    packDisplayNameEN: '协议源流组合包',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/协议源流组合包.webp',
    contents: [
      { itemId: 'item_ticketgacha_special_single', itemName: '特许寻访凭证', quantity: 10 },
      { itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 2000 },
      { itemId: 'item_char_skill_crown', itemName: '存续的痕迹', quantity: 10 },
    ],
  },
  seasonal_giftpack_lt_01: {
    packId: 'seasonal_giftpack_lt_01',
    packDisplayNameZH: '行火寻访组合包',
    packDisplayNameEN: '行火寻访组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/行火寻访组合包.webp',
    contents: [
      {
        itemId: 'item_ticketgacha_special_ten_lt_1_0_1',
        itemName: '行火留烬十连凭证',
        quantity: 1,
      },
      { itemId: 'item_gold', itemName: '折金票', quantity: 80_000 },
    ],
  },
  seasonal_giftpack_lt_02: {
    packId: 'seasonal_giftpack_lt_02',
    packDisplayNameZH: '异彩寻访组合包',
    packDisplayNameEN: '异彩寻访组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/异彩寻访组合包.webp',
    contents: [
      {
        itemId: 'item_ticketgacha_special_ten_lt_1_0_2',
        itemName: '异彩斑斓十连凭证',
        quantity: 1,
      },
      { itemId: 'item_gold', itemName: '折金票', quantity: 80_000 },
    ],
  },
  seasonal_giftpack_lt_03: {
    packId: 'seasonal_giftpack_lt_03',
    packDisplayNameZH: '信使寻访组合包',
    packDisplayNameEN: '信使寻访组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/信使寻访组合包.webp',
    contents: [
      {
        itemId: 'item_ticketgacha_special_ten_lt_1_0_3',
        itemName: '灵动信使十连凭证',
        quantity: 1,
      },
      { itemId: 'item_gold', itemName: '折金票', quantity: 80_000 },
    ],
  },
  monthly_giftpack_01: {
    packId: 'monthly_giftpack_01',
    packDisplayNameZH: '每月素材组合包',
    packDisplayNameEN: '每月素材组合包',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/每月素材组合包.webp',
    contents: [
      { itemId: 'item_gold', itemName: '折金票', quantity: 100_000 },
      { itemId: 'item_expcard_stage2_high', itemName: '高级认知载体', quantity: 10 },
      { itemId: 'item_weapon_expcard_high', itemName: '武器检查套组', quantity: 25 },
      { itemId: 'item_char_break_stage_3_4', itemName: '协议圆盘组', quantity: 20 },
      { itemId: 'item_weapon_break_high', itemName: '重型强固模具', quantity: 20 },
      { itemId: 'item_char_skill_level_7_12', itemName: '协议棱柱组', quantity: 50 },
      { itemId: 'item_case_bp_selfselect_skillsp_1', itemName: '高阶培养自选箱Ⅰ', quantity: 20 },
    ],
  },
  weekly_giftpack_01: {
    packId: 'weekly_giftpack_01',
    packDisplayNameZH: '每周素材组合包',
    packDisplayNameEN: '每周素材组合包',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/每周素材组合包.webp',
    contents: [
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_expcard_stage2_low', itemName: '初级认知载体', quantity: 120 },
      { itemId: 'item_weapon_expcard_mid', itemName: '武器检查装置', quantity: 240 },
    ],
  },
  特惠武库配额包: {
    packId: '特惠武库配额包',
    packDisplayNameZH: '特惠武库配额包',
    packDisplayNameEN: '特惠武库配额包',
    price: 88,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/特惠武库配额包.webp',
    contents: [{ itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 2000 }],
  },
  优惠武库配额包: {
    packId: '优惠武库配额包',
    packDisplayNameZH: '优惠武库配额包',
    packDisplayNameEN: '优惠武库配额包',
    price: 108,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/优惠武库配额包.webp',
    contents: [{ itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 2000 }],
  },
  标准武库配额包: {
    packId: '标准武库配额包',
    packDisplayNameZH: '标准武库配额包',
    packDisplayNameEN: '标准武库配额包',
    price: 128,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/标准武库配额包.webp',
    contents: [{ itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 2000 }],
  },
  月卡: {
    packId: '月卡',
    packDisplayNameZH: '月卡',
    packDisplayNameEN: '月卡',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/月卡.webp',
    contents: [
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 12 },
      { itemId: 'item_diamond', itemName: '嵌晶玉', quantity: 6000 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 30 },
    ],
  },
  '6元双倍源石': {
    packId: '6元双倍源石',
    packDisplayNameZH: '6元双倍源石',
    packDisplayNameEN: '6元双倍源石',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/6元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 6 }],
  },
  '30元双倍源石': {
    packId: '30元双倍源石',
    packDisplayNameZH: '30元双倍源石',
    packDisplayNameEN: '30元双倍源石',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/30元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 24 }],
  },
  '98元双倍源石': {
    packId: '98元双倍源石',
    packDisplayNameZH: '98元双倍源石',
    packDisplayNameEN: '98元双倍源石',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/98元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 84 }],
  },
  '198元双倍源石': {
    packId: '198元双倍源石',
    packDisplayNameZH: '198元双倍源石',
    packDisplayNameEN: '198元双倍源石',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/198元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 170 }],
  },
  '328元双倍源石': {
    packId: '328元双倍源石',
    packDisplayNameZH: '328元双倍源石',
    packDisplayNameEN: '328元双倍源石',
    price: 328,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/328元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 282 }],
  },
  '648元双倍源石': {
    packId: '648元双倍源石',
    packDisplayNameZH: '648元双倍源石',
    packDisplayNameEN: '648元双倍源石',
    price: 648,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/648元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 560 }],
  },
  '6元源石': {
    packId: '6元源石',
    packDisplayNameZH: '6元源石',
    packDisplayNameEN: '6元源石',
    price: 6,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/6元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 3 }],
  },
  '30元源石': {
    packId: '30元源石',
    packDisplayNameZH: '30元源石',
    packDisplayNameEN: '30元源石',
    price: 30,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/30元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 15 }],
  },
  '98元源石': {
    packId: '98元源石',
    packDisplayNameZH: '98元源石',
    packDisplayNameEN: '98元源石',
    price: 98,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/98元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 50 }],
  },
  '198元源石': {
    packId: '198元源石',
    packDisplayNameZH: '198元源石',
    packDisplayNameEN: '198元源石',
    price: 198,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/198元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 102 }],
  },
  '328元源石': {
    packId: '328元源石',
    packDisplayNameZH: '328元源石',
    packDisplayNameEN: '328元源石',
    price: 328,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/328元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 171 }],
  },
  '648元源石': {
    packId: '648元源石',
    packDisplayNameZH: '648元源石',
    packDisplayNameEN: '648元源石',
    price: 648,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/648元源石.webp',
    contents: [{ itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 350 }],
  },
  bp_track_pay: {
    packId: 'bp_track_pay',
    packDisplayNameZH: '协议定制',
    packDisplayNameEN: '协议定制',
    price: 68,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/协议定制.webp',
    contents: [
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 20 },
      { itemId: 'item_char_ap_supply_laevat', itemName: '海盐冰淇淋', quantity: 1 },
      { itemId: 'item_expcard_stage1_mid', itemName: '中级作战记录', quantity: 50 },
      { itemId: 'item_weapon_expcard_mid', itemName: '武器检查装置', quantity: 50 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 8 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 2 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_user_avatar_bp_1_0', itemName: '启程', quantity: 1 }, // 头像
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 2 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_case_bp_selfselect_break', itemName: '多用进阶自选箱', quantity: 2 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_user_avatar_frame_bp_1_0', itemName: '启程', quantity: 1 }, // 头像框
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 3 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_case_bp_selfselect_skill', itemName: '技能提升自选箱', quantity: 3 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_case_wpn_selfselect_bp_1', itemName: '武器补给·唤醒', quantity: 1 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 2 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_ap_feed_in', itemName: '理智萃取器', quantity: 5 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 800 },
      { itemId: 'item_char_ap_supply_yvonne', itemName: '草莓可丽饼', quantity: 1 },
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 5 },
      { itemId: 'item_case_bp_selfselect_break', itemName: '多用进阶自选箱', quantity: 5 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 50_000 },
      { itemId: 'item_wpnpotentialup_bp', itemName: '协议化武器原型', quantity: 1 },
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 8 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 20 },
      { itemId: 'item_case_bp_selfselect_skill', itemName: '技能提升自选箱', quantity: 8 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 65_000 },
      { itemId: 'business_card_topic_bp_1_0', itemName: '启程', quantity: 1 }, // 名片主题
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 4 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 20 },
      { itemId: 'item_ap_feed_in', itemName: '理智萃取器', quantity: 5 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 65_000 },
      { itemId: 'item_wpnpotentialup_bp', itemName: '协议化武器原型', quantity: 1 },
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 8 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 30 },
      { itemId: 'item_case_bp_selfselect_skillsp_1', itemName: '高阶培养自选箱Ⅰ', quantity: 8 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 80_000 },
      { itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 800 },
      { itemId: 'item_char_ap_supply_aglina', itemName: '栗花蜜', quantity: 1 },
      { itemId: 'item_case_bp_selfselect_skill', itemName: '技能提升自选箱', quantity: 6 },
      { itemId: 'item_case_bp_selfselect_skillsp_1', itemName: '高阶培养自选箱Ⅰ', quantity: 6 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 80_000 },
      { itemId: 'item_char_skill_crown', itemName: '存续的痕迹', quantity: 10 },
      { itemId: 'item_case_bp_selfselect_exp', itemName: '多用经验自选箱', quantity: 10 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 30 },
      { itemId: 'item_case_bp_selfselect_skillsp_1', itemName: '高阶培养自选箱Ⅰ', quantity: 10 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 100_000 },
      { itemId: 'item_gachabyproducts_weapongold', itemName: '武库配额', quantity: 800 },
      { itemId: 'item_case_bp_selfselect_skill', itemName: '技能提升自选箱', quantity: 10 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 30 },
      { itemId: 'item_case_bp_selfselect_skillsp_1', itemName: '高阶培养自选箱Ⅰ', quantity: 10 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 100_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 8 },
    ],
  },
  bp_track_originium: {
    packId: 'bp_track_originium',
    packDisplayNameZH: '源石配给',
    packDisplayNameEN: '源石配给',
    descriptionZH: '价格为源石折算',
    descriptionEN: '价格为源石折算',
    price: Math.round((29 / 350) * 648 * 10) / 10,
    imageUrl: 'https://cos.yituliu.cn/endfield/screenshot-images/packs/源石配给.webp',
    contents: [
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: 'item_expcard_stage1_mid', itemName: '中级作战记录', quantity: 30 },
      { itemId: 'item_weapon_expcard_mid', itemName: '武器检查装置', quantity: 30 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 15_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 5 },
      { itemId: 'item_expcard_stage1_mid', itemName: '中级作战记录', quantity: 30 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 5 },
      { itemId: 'item_weapon_expcard_mid', itemName: '武器检查装置', quantity: 30 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 15_000 },
      { itemId: 'item_shot_sticker_bp_1', itemName: '贴纸·记忆', quantity: 1 },
      { itemId: 'item_char_break_stage_1_2', itemName: '协议圆盘', quantity: 15 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 5 },
      { itemId: 'item_weapon_break_low', itemName: '强固模具', quantity: 15 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 15_000 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 2 },
      { itemId: 'item_expcard_stage1_high', itemName: '高级作战记录', quantity: 10 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 5 },
      { itemId: 'item_weapon_expcard_high', itemName: '武器检查套组', quantity: 10 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 20_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 5 },
      { itemId: 'item_char_skill_level_1_6', itemName: '协议棱柱', quantity: 50 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 5 },
      { itemId: 'item_char_skill_level_1_6', itemName: '协议棱柱', quantity: 50 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 20_000 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 3 },
      { itemId: 'item_expcard_stage2_high', itemName: '高级认知载体', quantity: 8 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: 'item_weapon_expcard_high', itemName: '武器检查套组', quantity: 20 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 30_000 },
      { itemId: 'item_shot_filter_sp_1', itemName: '滤镜·黑金', quantity: 1 },
      { itemId: 'item_char_break_stage_3_4', itemName: '协议圆盘组', quantity: 10 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_weapon_break_high', itemName: '重型强固模具', quantity: 10 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 40_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 5 },
      { itemId: 'item_char_skill_level_7_12', itemName: '协议棱柱组', quantity: 20 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 10 },
      { itemId: 'item_char_skill_level_7_12', itemName: '协议棱柱组', quantity: 20 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 40_000 },
      { itemId: 'item_case_wpn_selfselect_bp_1', itemName: '武器补给·唤醒', quantity: 1 },
      { itemId: 'item_expcard_stage2_high', itemName: '高级认知载体', quantity: 10 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 15 },
      { itemId: 'item_weapon_expcard_high', itemName: '武器检查套组', quantity: 25 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 50_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 5 },
      { itemId: 'item_char_break_stage_3_4', itemName: '协议圆盘组', quantity: 20 },
      { itemId: 'item_ap_supply_lt_n', itemName: '应急理智加强剂', quantity: 1 },
      { itemId: 'item_weapon_break_high', itemName: '重型强固模具', quantity: 20 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 50_000 },
      { itemId: 'item_char_skill_crown', itemName: '存续的痕迹', quantity: 6 },
      { itemId: 'item_char_skill_level_7_12', itemName: '协议棱柱组', quantity: 30 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 15 },
      { itemId: 'item_char_skill_level_7_12', itemName: '协议棱柱组', quantity: 30 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 60_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 5 },
      { itemId: 'item_expcard_stage2_high', itemName: '高级认知载体', quantity: 12 },
      { itemId: 'item_bp_double_reward', itemName: '理智消耗许可', quantity: 15 },
      { itemId: 'item_weapon_expcard_high', itemName: '武器检查套组', quantity: 30 },
      { itemId: 'item_gold', itemName: '折金票', quantity: 60_000 },
      { itemId: 'item_originium_recharge', itemName: '衍质源石', quantity: 7 },
    ],
  },
};
