export interface ShopItem {
  itemId: string;
  itemName?: string;
  quantityPerGroup: number; // 每组数量
  stockGroups?: number; // 库存组数
  originalPrice?: number; // 原价
  discount?: number; // 折扣
  currentPrice: number; // 现价
}

export interface Shop {
  shopId: string;
  shopName: string;
  shopItems: ShopItem[];
}

export const shops: Shop[] = [
  {
    shopId: '保障配额交易',
    shopName: '保障配额交易',
    shopItems: [
      {
        itemId: '行火留烬寻访凭证',
        itemName: '行火留烬寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 25,
        discount: -0.4,
        currentPrice: 15,
      },
      {
        itemId: '艾维文娜',
        itemName: '艾维文娜',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 200,
        discount: 0,
        currentPrice: 200,
      },
      {
        itemId: '存续的痕迹',
        itemName: '存续的痕迹',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: '特许寻访凭证',
        itemName: '特许寻访凭证',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: '超距辉映管',
        itemName: '超距辉映管',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'D96钢样品四',
        itemName: 'D96钢样品四',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '快子遴捡晶格',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '象限拟合液',
        itemName: '象限拟合液',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '三相纳米片',
        itemName: '三相纳米片',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
    ],
  },
  {
    shopId: '集成配额交易',
    shopName: '集成配额交易',
    shopItems: [
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: 5,
        originalPrice: 40,
        discount: -0.25,
        currentPrice: 30,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: 8,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 12000,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '高级作战记录',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '超距辉映管',
        itemName: '超距辉映管',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'D96钢样品四',
        itemName: 'D96钢样品四',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '快子遴捡晶格',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '象限拟合液',
        itemName: '象限拟合液',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '三相纳米片',
        itemName: '三相纳米片',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 12000,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '高级作战记录',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 30,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
    ],
  },
  {
    shopId: '信用交易所',
    shopName: '信用交易所',
    shopItems: [
      {
        itemId: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: '初级作战记录',
        quantityPerGroup: 30,
        stockGroups: 1,
        originalPrice: 90,
        discount: 0,
        currentPrice: 90,
      },
      {
        itemId: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: '协议棱柱',
        quantityPerGroup: 4,
        stockGroups: 1,
        originalPrice: 120,
        discount: 0,
        currentPrice: 120,
      },
      {
        itemId: '强固模具',
        quantityPerGroup: 2,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: '嵌晶玉',
        quantityPerGroup: 25,
        stockGroups: 1,
        originalPrice: 400,
        discount: 0,
        currentPrice: 400,
      },
      {
        itemId: '武器检查单元',
        quantityPerGroup: 30,
        stockGroups: 1,
        originalPrice: 90,
        discount: 0,
        currentPrice: 90,
      },
      {
        itemId: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: '武库配额',
        quantityPerGroup: 20,
        stockGroups: 1,
        originalPrice: 840,
        discount: 0,
        currentPrice: 840,
      },
      {
        itemId: '协议圆盘',
        quantityPerGroup: 2,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
    ],
  },
  {
    shopId: '四号谷地物资调度 − 稳定需求物资',
    shopName: '四号谷地物资调度 − 稳定需求物资',
    shopItems: [
      // 日用消耗
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.98,
        currentPrice: 1000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.96,
        currentPrice: 2000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.88,
        currentPrice: 6000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.84,
        currentPrice: 8000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.76,
        currentPrice: 12000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.6,
        currentPrice: 20000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.4,
        currentPrice: 30000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: 0,
        currentPrice: 50000,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 10,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 38,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: '初级认知载体',
        itemName: '初级认知载体',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 1250,
        discount: 0,
        currentPrice: 1250,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.9,
        currentPrice: 250,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.64,
        currentPrice: 900,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 2,
        originalPrice: 2500,
        discount: -0.4,
        currentPrice: 1500,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 6,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: 2,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.9,
        currentPrice: 250,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.64,
        currentPrice: 900,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 2,
        originalPrice: 2500,
        discount: -0.4,
        currentPrice: 1500,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 6,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: 2,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 3,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 8,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 28,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantityPerGroup: 2,
        stockGroups: 5,
        originalPrice: 2000,
        discount: 0,
        currentPrice: 2000,
      },
      {
        itemId: '武器检查装置',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 6,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: '武器检查装置',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 7,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: '武器检查装置',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 4,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: '武器检查装置',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 19,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: '中级作战记录',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 6,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: '中级作战记录',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 7,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: '中级作战记录',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 4,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: '中级作战记录',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 15,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: '谷地刻写券',
        itemName: '谷地刻写券',
        quantityPerGroup: 1,
        stockGroups: 12,
        originalPrice: 800000,
        discount: -0.5,
        currentPrice: 400000,
      },
      {
        itemId: '谷地刻写券',
        itemName: '谷地刻写券',
        quantityPerGroup: 1,
        stockGroups: 24,
        originalPrice: 800000,
        discount: 0,
        currentPrice: 800000,
      },
      {
        itemId: '附术铁瓶',
        itemName: '附术铁瓶',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200000,
        discount: -0.5,
        currentPrice: 100000,
      },
      {
        itemId: '雅各布的遗产',
        itemName: '雅各布的遗产',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200000,
        discount: -0.3,
        currentPrice: 140000,
      },
      {
        itemId: '手撕虫肉',
        itemName: '手撕虫肉',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200000,
        discount: -0.3,
        currentPrice: 140000,
      },
      {
        itemId: '附术铁瓶',
        itemName: '附术铁瓶',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200000,
        discount: 0,
        currentPrice: 200000,
      },
      {
        itemId: '雅各布的遗产',
        itemName: '雅各布的遗产',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200000,
        discount: 0,
        currentPrice: 200000,
      },
      {
        itemId: '手撕虫肉',
        itemName: '手撕虫肉',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200000,
        discount: 0,
        currentPrice: 200000,
      },
      {
        itemId: '雾火之花',
        itemName: '雾火之花',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 120000,
        discount: -0.8,
        currentPrice: 24000,
      },
      {
        itemId: '软骨饼干',
        itemName: '软骨饼干',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 120000,
        discount: -0.8,
        currentPrice: 24000,
      },
      {
        itemId: '星融果冻',
        itemName: '星融果冻',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 120000,
        discount: -0.5,
        currentPrice: 60000,
      },
      {
        itemId: '雾火之花',
        itemName: '雾火之花',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120000,
        discount: 0,
        currentPrice: 120000,
      },
      {
        itemId: '软骨饼干',
        itemName: '软骨饼干',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120000,
        discount: 0,
        currentPrice: 120000,
      },
      {
        itemId: '星融果冻',
        itemName: '星融果冻',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120000,
        discount: 0,
        currentPrice: 120000,
      },
      // 工业货品
      {
        itemId: '坚城铸造者',
        itemName: '坚城铸造者',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.98,
        currentPrice: 1000,
      },
      {
        itemId: '探骊',
        itemName: '探骊',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.96,
        currentPrice: 2000,
      },
      {
        itemId: '作品：众生',
        itemName: '作品：众生',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: '布道自由',
        itemName: '布道自由',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.88,
        currentPrice: 6000,
      },
      {
        itemId: '终点之声',
        itemName: '终点之声',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.84,
        currentPrice: 8000,
      },
      {
        itemId: '向心之引',
        itemName: '向心之引',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.76,
        currentPrice: 12000,
      },
      {
        itemId: '莫奈何',
        itemName: '莫奈何',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.6,
        currentPrice: 20000,
      },
      {
        itemId: '十二问',
        itemName: '十二问',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.4,
        currentPrice: 30000,
      },
      {
        itemId: '仰止',
        itemName: '仰止',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: 0,
        currentPrice: 50000,
      },
      {
        itemId: '新锐谷地罗盘',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.99,
        currentPrice: 1000,
      },
      {
        itemId: '新锐谷地探物器',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.99,
        currentPrice: 1000,
      },
      {
        itemId: '新锐谷地罗盘',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.95,
        currentPrice: 5000,
      },
      {
        itemId: '新锐谷地探物器',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.95,
        currentPrice: 5000,
      },
      {
        itemId: '新锐谷地罗盘',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 100000,
        discount: -0.8,
        currentPrice: 20000,
      },
      {
        itemId: '新锐谷地探物器',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 100000,
        discount: -0.8,
        currentPrice: 20000,
      },
      {
        itemId: '新锐谷地罗盘',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.5,
        currentPrice: 50000,
      },
      {
        itemId: '新锐谷地探物器',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100000,
        discount: -0.5,
        currentPrice: 50000,
      },
      {
        itemId: '新锐谷地罗盘',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 100000,
        discount: 0,
        currentPrice: 100000,
      },
      {
        itemId: '新锐谷地探物器',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 100000,
        discount: 0,
        currentPrice: 100000,
      },
      // 人文物产
      {
        itemId: '弧线2000模型',
        itemName: '弧线2000模型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16000000,
        discount: 0,
        currentPrice: 16000000,
      },
      {
        itemId: '冠军钻探器',
        itemName: '冠军钻探器',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16000000,
        discount: 0,
        currentPrice: 16000000,
      },
      {
        itemId: '生机盆景',
        itemName: '生机盆景',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16000000,
        discount: 0,
        currentPrice: 16000000,
      },
      {
        itemId: '醚质相机',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '星门锁',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '冲浪大赛门票',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '耶尔什微风',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '浪潮海石',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '赛梦珂披巾',
        itemName: '赛梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '《前沿瞭望》',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: '醚质相机',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '星门锁',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '冲浪大赛门票',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '耶尔什微风',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '浪潮海石',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '赛梦珂披巾',
        itemName: '赛梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '《前沿瞭望》',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '醚质相机',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '星门锁',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '冲浪大赛门票',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '耶尔什微风',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '浪潮海石',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '赛梦珂披巾',
        itemName: '赛梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '《前沿瞭望》',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30000,
        discount: 0,
        currentPrice: 30000,
      },
      {
        itemId: '兰姆先生',
        itemName: '兰姆先生',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 10000,
        discount: -0.99,
        currentPrice: 100,
      },
    ],
  },
  {
    shopId: '武陵物资调度 − 稳定需求物资',
    shopName: '武陵物资调度 − 稳定需求物资',
    shopItems: [
      // 日用消耗
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: '基础寻访凭证',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50000,
        discount: -0.85,
        currentPrice: 7500,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 10000,
        stockGroups: 10,
        originalPrice: 5000,
        discount: -0.95,
        currentPrice: 500,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 10000,
        stockGroups: 10,
        originalPrice: 5000,
        discount: -0.9,
        currentPrice: 1000,
      },
      {
        itemId: '武陵刻写券',
        itemName: '武陵刻写券',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 1600000,
        discount: -0.92,
        currentPrice: 128000,
      },
      {
        itemId: '武陵刻写券',
        itemName: '武陵刻写券',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 1600000,
        discount: -0.85,
        currentPrice: 240000,
      },
      {
        itemId: '正本补元汤剂',
        itemName: '正本补元汤剂',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 300000,
        discount: -0.95,
        currentPrice: 15000,
      },
      {
        itemId: '锦素炒饭',
        itemName: '锦素炒饭',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 300000,
        discount: -0.95,
        currentPrice: 15000,
      },
      {
        itemId: '正本补元汤剂',
        itemName: '正本补元汤剂',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 300000,
        discount: -0.9,
        currentPrice: 30000,
      },
      {
        itemId: '锦素炒饭',
        itemName: '锦素炒饭',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 300000,
        discount: -0.9,
        currentPrice: 30000,
      },
      // 工业货品
      {
        itemId: '武陵精锻助剂',
        itemName: '武陵精锻助剂',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 800000,
        discount: -0.92,
        currentPrice: 64000,
      },
      {
        itemId: '武陵精锻助剂',
        itemName: '武陵精锻助剂',
        quantityPerGroup: 1,
        stockGroups: 20,
        originalPrice: 800000,
        discount: -0.85,
        currentPrice: 120000,
      },
      {
        itemId: '新锐武陵罗盘',
        itemName: '新锐武陵罗盘',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200000,
        discount: -0.92,
        currentPrice: 16000,
      },
      {
        itemId: '新锐武陵探物器',
        itemName: '新锐武陵探物器',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200000,
        discount: -0.92,
        currentPrice: 16000,
      },
      {
        itemId: '新锐武陵罗盘',
        itemName: '新锐武陵罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 200000,
        discount: -0.85,
        currentPrice: 30000,
      },
      {
        itemId: '新锐武陵探物器',
        itemName: '新锐武陵探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 200000,
        discount: -0.85,
        currentPrice: 30000,
      },
      {
        itemId: '碾骨小雕像·壹型',
        itemName: '碾骨小雕像·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '动火用电力匣',
        itemName: '动火用电力匣',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '纾难识别牌',
        itemName: '纾难识别牌',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '纾难识别牌·壹型',
        itemName: '纾难识别牌·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '纾难印章',
        itemName: '纾难印章',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '纾难印章·壹型',
        itemName: '纾难印章·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '生物辅助接驳器·壹型',
        itemName: '生物辅助接驳器·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'M.I.警用刺刃·壹型',
        itemName: 'M.I.警用刺刃·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '50式应龙短刃',
        itemName: '50式应龙短刃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: '50式应龙短刃·壹型',
        itemName: '50式应龙短刃·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'M.I.警用罩衣·贰型',
        itemName: 'M.I.警用罩衣·贰型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'M.I.警用臂环',
        itemName: 'M.I.警用臂环',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'M.I.警用瞄具',
        itemName: 'M.I.警用瞄具',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'M.1.警用工具组',
        itemName: 'M.1.警用工具组',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      // 人文物产
      {
        itemId: '天师桩模型',
        itemName: '天师桩模型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 4000000,
        discount: 0,
        currentPrice: 4000000,
      },
      {
        itemId: '岳研茶盒',
        itemName: '岳研茶盒',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60000,
        discount: -0.92,
        currentPrice: 4800,
      },
      {
        itemId: '应龙哑铃',
        itemName: '应龙哑铃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60000,
        discount: -0.92,
        currentPrice: 4800,
      },
      {
        itemId: '岳研茶盒',
        itemName: '岳研茶盒',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60000,
        discount: -0.85,
        currentPrice: 9000,
      },
      {
        itemId: '应龙哑铃',
        itemName: '应龙哑铃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60000,
        discount: -0.85,
        currentPrice: 9000,
      },
    ],
  },
];
