export interface Shop {
  shopId: string;
  shopName: string;
  shopItems: {
    itemId: string;
    itemName?: string;
    quantityPerGroup: number; // 每组数量
    stockGroups?: number; // 库存组数
    originalPrice?: number; // 原价
    discount?: number; // 折扣
    currentPrice: number; // 现价
  }[];
}

export const shops: Shop[] = [
  {
    shopId: '保障配额交易',
    shopName: '保障配额交易',
    shopItems: [
      {
        itemId: '行火留烬寻访凭证',
        itemName: '行火留烬寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 25,
        discount: -0.4,
        currentPrice: 15,
      },
      {
        itemId: '艾维文娜',
        itemName: '艾维文娜',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 200,
        discount: 0,
        currentPrice: 200,
      },
      {
        itemId: '存续的痕迹',
        itemName: '存续的痕迹',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: '特许寻访凭证',
        itemName: '特许寻访凭证',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: '超距辉映管',
        itemName: '超距辉映管',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'D96钢样品四',
        itemName: 'D96钢样品四',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '快子遴捡晶格',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '象限拟合液',
        itemName: '象限拟合液',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '三相纳米片',
        itemName: '三相纳米片',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
    ],
  },
  {
    shopId: '集成配额交易',
    shopName: '集成配额交易',
    shopItems: [
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: 5,
        originalPrice: 40,
        discount: -0.25,
        currentPrice: 30,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: 8,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 12000,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '高级作战记录',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: '高级认知载体',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '超距辉映管',
        itemName: '超距辉映管',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'D96钢样品四',
        itemName: 'D96钢样品四',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '快子遴捡晶格',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '象限拟合液',
        itemName: '象限拟合液',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '三相纳米片',
        itemName: '三相纳米片',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: '武器检查套组',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议棱柱组',
        itemName: '协议棱柱组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议圆盘组',
        itemName: '协议圆盘组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: '重型强固模具',
        itemName: '重型强固模具',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: '折金票',
        itemName: '折金票',
        quantityPerGroup: 12000,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '高级作战记录',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议棱柱',
        itemName: '协议棱柱',
        quantityPerGroup: 30,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: '协议圆盘',
        itemName: '协议圆盘',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
      {
        itemId: '强固模具',
        itemName: '强固模具',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
    ],
  },
];
