// 本文件中的 itemName 字段仅作为备注使用，请勿依赖其值进行逻辑处理

export interface ShopItem {
  itemId: string;
  itemName?: string;
  quantityPerGroup: number; // 每组数量
  stockGroups?: number; // 库存组数
  originalPrice?: number; // 原价
  discount?: number; // 折扣
  currentPrice: number; // 现价
}

export interface Shop {
  shopId: string;
  shopName: string;
  shopItems: ShopItem[];
}

export const shops: Shop[] = [
  {
    shopId: '危机合约·机密圣所',
    shopName: '危机合约·机密圣所',
    shopItems: [
      {
        itemId: 'item_wpngem_enhance_dust',
        itemName: '冷却脂',
        quantityPerGroup: 10,
        stockGroups: 30,
        originalPrice: 15,
        discount: -0.3,
        currentPrice: 10,
      },
      {
        itemId: 'item_case_bp_selfselect_skillsp_1',
        itemName: '高阶培养自选箱Ⅰ',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30,
        discount: -0.3,
        currentPrice: 21,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 10_000,
        stockGroups: 15,
        originalPrice: 30,
        discount: -0.3,
        currentPrice: 21,
      },
      {
        itemId: 'item_char_skill_level_7_12',
        itemName: '协议棱柱组',
        quantityPerGroup: 3,
        stockGroups: 15,
        originalPrice: 20,
        discount: -0.3,
        currentPrice: 14,
      },
      {
        itemId: 'item_char_skill_crown',
        itemName: '存续的痕迹',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 60,
        discount: 0,
        currentPrice: 60,
      },
      {
        itemId: 'item_wpngem_enhance_dust',
        itemName: '冷却脂',
        quantityPerGroup: 10,
        stockGroups: 30,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_specialize_1',
        itemName: '超距辉映管',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_specialize_2',
        itemName: 'D96钢样品四',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_specialize_3',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_specialize_4',
        itemName: '象限拟合液',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_specialize_5',
        itemName: '三相纳米片',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30,
        discount: 0,
        currentPrice: 30,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 10_000,
        stockGroups: 30,
        originalPrice: 30,
        discount: 0,
        currentPrice: 30,
      },
      {
        itemId: 'item_expcard_stage2_high',
        itemName: '高级认知载体',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_break_stage_3_4',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: 10,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_char_skill_level_7_12',
        itemName: '协议棱柱组',
        quantityPerGroup: 3,
        stockGroups: 60,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_weapon_expcard_high',
        itemName: '武器检查套组',
        quantityPerGroup: 3,
        stockGroups: 20,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_weapon_break_high',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: 10,
        originalPrice: 15,
        discount: 0,
        currentPrice: 15,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 500,
        stockGroups: Infinity,
        originalPrice: 5,
        discount: 0,
        currentPrice: 5,
      },
      {
        itemId: 'item_diamond',
        itemName: '嵌晶玉',
        quantityPerGroup: 100,
        stockGroups: 20,
        originalPrice: 50,
        discount: 0,
        currentPrice: 50,
      },
    ],
  },
  {
    shopId: '保障配额交易',
    shopName: '保障配额交易',
    shopItems: [
      {
        itemId: 'item_ticketgacha_special_single_lt_1_0_1',
        itemName: '行火留烬寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 25,
        discount: -0.4,
        currentPrice: 15,
      },
      {
        itemId: 'chr_0012_avywen',
        itemName: '艾维文娜',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 200,
        discount: 0,
        currentPrice: 200,
      },
      {
        itemId: 'item_char_skill_crown',
        itemName: '存续的痕迹',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: 'item_ticketgacha_special_single',
        itemName: '特许寻访凭证',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 25,
        discount: 0,
        currentPrice: 25,
      },
      {
        itemId: 'item_char_skill_specialize_1',
        itemName: '超距辉映管',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_char_skill_specialize_2',
        itemName: 'D96钢样品四',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_char_skill_specialize_3',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_char_skill_specialize_4',
        itemName: '象限拟合液',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_char_skill_specialize_5',
        itemName: '三相纳米片',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_expcard_stage2_high',
        itemName: '高级认知载体',
        quantityPerGroup: 1,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_weapon_expcard_high',
        itemName: '武器检查套组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
      {
        itemId: 'item_char_break_stage_3_4',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_weapon_break_high',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 4,
        discount: 0,
        currentPrice: 4,
      },
      {
        itemId: 'item_char_skill_level_7_12',
        itemName: '协议棱柱组',
        quantityPerGroup: 2,
        stockGroups: Infinity,
        originalPrice: 3,
        discount: 0,
        currentPrice: 3,
      },
    ],
  },
  {
    shopId: '集成配额交易',
    shopName: '集成配额交易',
    shopItems: [
      {
        itemId: 'item_expcard_stage2_high',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: 5,
        originalPrice: 40,
        discount: -0.25,
        currentPrice: 30,
      },
      {
        itemId: 'item_weapon_expcard_high',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: 8,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 12_000,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: 'item_expcard_stage1_high',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: 5,
        originalPrice: 20,
        discount: -0.25,
        currentPrice: 15,
      },
      {
        itemId: 'item_expcard_stage2_high',
        itemName: '高级认知载体',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_char_skill_specialize_1',
        itemName: '超距辉映管',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_char_skill_specialize_2',
        itemName: 'D96钢样品四',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_char_skill_specialize_3',
        itemName: '快子遴捡晶格',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_char_skill_specialize_4',
        itemName: '象限拟合液',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_char_skill_specialize_5',
        itemName: '三相纳米片',
        quantityPerGroup: 5,
        stockGroups: Infinity,
        originalPrice: 40,
        discount: 0,
        currentPrice: 40,
      },
      {
        itemId: 'item_weapon_expcard_high',
        itemName: '武器检查套组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_char_skill_level_7_12',
        itemName: '协议棱柱组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_char_break_stage_3_4',
        itemName: '协议圆盘组',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: 'item_weapon_break_high',
        itemName: '重型强固模具',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 24,
        discount: 0,
        currentPrice: 24,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 12_000,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_expcard_stage1_high',
        itemName: '高级作战记录',
        quantityPerGroup: 6,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        itemName: '协议棱柱',
        quantityPerGroup: 30,
        stockGroups: Infinity,
        originalPrice: 20,
        discount: 0,
        currentPrice: 20,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        itemName: '协议圆盘',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
      {
        itemId: 'item_weapon_break_low',
        itemName: '强固模具',
        quantityPerGroup: 8,
        stockGroups: Infinity,
        originalPrice: 16,
        discount: 0,
        currentPrice: 16,
      },
    ],
  },
  {
    shopId: '信用交易所',
    shopName: '信用交易所',
    shopItems: [
      {
        itemId: 'item_gold',
        quantityPerGroup: 2000,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: 'item_expcard_stage1_low',
        quantityPerGroup: 30,
        stockGroups: 1,
        originalPrice: 90,
        discount: 0,
        currentPrice: 90,
      },
      {
        itemId: 'item_expcard_stage1_mid',
        quantityPerGroup: 10,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        quantityPerGroup: 4,
        stockGroups: 1,
        originalPrice: 120,
        discount: 0,
        currentPrice: 120,
      },
      {
        itemId: 'item_weapon_break_low',
        quantityPerGroup: 2,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: 'item_diamond',
        quantityPerGroup: 25,
        stockGroups: 1,
        originalPrice: 400,
        discount: 0,
        currentPrice: 400,
      },
      {
        itemId: 'item_weapon_expcard_low',
        quantityPerGroup: 30,
        stockGroups: 1,
        originalPrice: 90,
        discount: 0,
        currentPrice: 90,
      },
      {
        itemId: 'item_weapon_expcard_mid',
        quantityPerGroup: 10,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
      {
        itemId: 'item_gachabyproducts_weapongold',
        quantityPerGroup: 20,
        stockGroups: 1,
        originalPrice: 840,
        discount: 0,
        currentPrice: 840,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        quantityPerGroup: 2,
        stockGroups: 1,
        originalPrice: 140,
        discount: 0,
        currentPrice: 140,
      },
    ],
  },
  {
    shopId: '四号谷地物资调度 − 稳定需求物资',
    shopName: '四号谷地物资调度 − 稳定需求物资',
    shopItems: [
      // 日用消耗
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.98,
        currentPrice: 1000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.96,
        currentPrice: 2000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.88,
        currentPrice: 6000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.84,
        currentPrice: 8000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.76,
        currentPrice: 12_000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.6,
        currentPrice: 20_000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.4,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: 0,
        currentPrice: 50_000,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 10,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 2000,
        stockGroups: 38,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: 'item_expcard_stage2_low',
        itemName: '初级认知载体',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 1250,
        discount: 0,
        currentPrice: 1250,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.9,
        currentPrice: 250,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.64,
        currentPrice: 900,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 2,
        originalPrice: 2500,
        discount: -0.4,
        currentPrice: 1500,
      },
      {
        itemId: 'item_char_break_stage_1_2',
        itemName: '协议圆盘',
        quantityPerGroup: 5,
        stockGroups: 6,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: 'item_char_break_stage_3_4',
        itemName: '协议圆盘组',
        quantityPerGroup: 2,
        stockGroups: 2,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: 'item_weapon_break_low',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.9,
        currentPrice: 250,
      },
      {
        itemId: 'item_weapon_break_low',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 4,
        originalPrice: 2500,
        discount: -0.64,
        currentPrice: 900,
      },
      {
        itemId: 'item_weapon_break_low',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 2,
        originalPrice: 2500,
        discount: -0.4,
        currentPrice: 1500,
      },
      {
        itemId: 'item_weapon_break_low',
        itemName: '强固模具',
        quantityPerGroup: 5,
        stockGroups: 6,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: 'item_weapon_break_high',
        itemName: '重型强固模具',
        quantityPerGroup: 2,
        stockGroups: 2,
        originalPrice: 2500,
        discount: 0,
        currentPrice: 2500,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 3,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 8,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 5,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: 'item_char_skill_level_1_6',
        itemName: '协议棱柱',
        quantityPerGroup: 5,
        stockGroups: 28,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: 'item_char_skill_level_7_12',
        itemName: '协议棱柱组',
        quantityPerGroup: 2,
        stockGroups: 5,
        originalPrice: 2000,
        discount: 0,
        currentPrice: 2000,
      },
      {
        itemId: 'item_weapon_expcard_mid',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 6,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: 'item_weapon_expcard_mid',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 7,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: 'item_weapon_expcard_mid',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 4,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: 'item_weapon_expcard_mid',
        itemName: '武器检查装置',
        quantityPerGroup: 10,
        stockGroups: 19,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: 'item_expcard_stage1_mid',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 6,
        originalPrice: 1000,
        discount: -0.9,
        currentPrice: 100,
      },
      {
        itemId: 'item_expcard_stage1_mid',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 7,
        originalPrice: 1000,
        discount: -0.64,
        currentPrice: 360,
      },
      {
        itemId: 'item_expcard_stage1_mid',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 4,
        originalPrice: 1000,
        discount: -0.4,
        currentPrice: 600,
      },
      {
        itemId: 'item_expcard_stage1_mid',
        itemName: '中级作战记录',
        quantityPerGroup: 10,
        stockGroups: 15,
        originalPrice: 1000,
        discount: 0,
        currentPrice: 1000,
      },
      {
        itemId: 'item_gem_stable_energy_point_tundra',
        itemName: '谷地刻写券',
        quantityPerGroup: 1,
        stockGroups: 12,
        originalPrice: 800_000,
        discount: -0.5,
        currentPrice: 400_000,
      },
      {
        itemId: 'item_gem_stable_energy_point_tundra',
        itemName: '谷地刻写券',
        quantityPerGroup: 1,
        stockGroups: 24,
        originalPrice: 800_000,
        discount: 0,
        currentPrice: 800_000,
      },
      {
        itemId: 'item_bottled_insec2_2',
        itemName: '附术铁瓶',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200_000,
        discount: -0.5,
        currentPrice: 100_000,
      },
      {
        itemId: 'item_agrange_1_erhound_1_sp_1_1',
        itemName: '雅各布的遗产',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200_000,
        discount: -0.3,
        currentPrice: 140_000,
      },
      {
        itemId: 'item_slimeml_1_erhound_1_agfly_1_1',
        itemName: '手撕虫肉',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200_000,
        discount: -0.3,
        currentPrice: 140_000,
      },
      {
        itemId: 'item_bottled_insec2_2',
        itemName: '附术铁瓶',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200_000,
        discount: 0,
        currentPrice: 200_000,
      },
      {
        itemId: 'item_agrange_1_erhound_1_sp_1_1',
        itemName: '雅各布的遗产',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200_000,
        discount: 0,
        currentPrice: 200_000,
      },
      {
        itemId: 'item_slimeml_1_erhound_1_agfly_1_1',
        itemName: '手撕虫肉',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 200_000,
        discount: 0,
        currentPrice: 200_000,
      },
      {
        itemId: 'item_erhound_1_agmelee_1_moss_1_1',
        itemName: '雾火之花',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 120_000,
        discount: -0.8,
        currentPrice: 24_000,
      },
      {
        itemId: 'item_lbmob_1_lbshamman_1_sp_1_1',
        itemName: '软骨饼干',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 120_000,
        discount: -0.8,
        currentPrice: 24_000,
      },
      {
        itemId: 'item_agfly_1_agmelee_1_moss_2_1',
        itemName: '星融果冻',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 120_000,
        discount: -0.5,
        currentPrice: 60_000,
      },
      {
        itemId: 'item_erhound_1_agmelee_1_moss_1_1',
        itemName: '雾火之花',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120_000,
        discount: 0,
        currentPrice: 120_000,
      },
      {
        itemId: 'item_lbmob_1_lbshamman_1_sp_1_1',
        itemName: '软骨饼干',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120_000,
        discount: 0,
        currentPrice: 120_000,
      },
      {
        itemId: 'item_agfly_1_agmelee_1_moss_2_1',
        itemName: '星融果冻',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 120_000,
        discount: 0,
        currentPrice: 120_000,
      },
      // 工业货品
      {
        itemId: 'wpn_sword_0007',
        itemName: '坚城铸造者',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.98,
        currentPrice: 1000,
      },
      {
        itemId: 'wpn_claym_0011',
        itemName: '探骊',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.96,
        currentPrice: 2000,
      },
      {
        itemId: 'wpn_pistol_0006',
        itemName: '作品：众生',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: 'wpn_funnel_0012',
        itemName: '布道自由',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.88,
        currentPrice: 6000,
      },
      {
        itemId: 'wpn_claym_0012',
        itemName: '终点之声',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.84,
        currentPrice: 8000,
      },
      {
        itemId: 'wpn_lance_0006',
        itemName: '向心之引',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.76,
        currentPrice: 12_000,
      },
      {
        itemId: 'wpn_funnel_0007',
        itemName: '莫奈何',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.6,
        currentPrice: 20_000,
      },
      {
        itemId: 'wpn_sword_0018',
        itemName: '十二问',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.4,
        currentPrice: 30_000,
      },
      {
        itemId: 'wpn_sword_0015',
        itemName: '仰止',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: 0,
        currentPrice: 50_000,
      },
      {
        itemId: 'item_tundra_detector_coin_3',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.99,
        currentPrice: 1000,
      },
      {
        itemId: 'item_tundra_detector_trchest_3',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.99,
        currentPrice: 1000,
      },
      {
        itemId: 'item_tundra_detector_coin_3',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.95,
        currentPrice: 5000,
      },
      {
        itemId: 'item_tundra_detector_trchest_3',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.95,
        currentPrice: 5000,
      },
      {
        itemId: 'item_tundra_detector_coin_3',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 100_000,
        discount: -0.8,
        currentPrice: 20_000,
      },
      {
        itemId: 'item_tundra_detector_trchest_3',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 100_000,
        discount: -0.8,
        currentPrice: 20_000,
      },
      {
        itemId: 'item_tundra_detector_coin_3',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.5,
        currentPrice: 50_000,
      },
      {
        itemId: 'item_tundra_detector_trchest_3',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 100_000,
        discount: -0.5,
        currentPrice: 50_000,
      },
      {
        itemId: 'item_tundra_detector_coin_3',
        itemName: '新锐谷地罗盘',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 100_000,
        discount: 0,
        currentPrice: 100_000,
      },
      {
        itemId: 'item_tundra_detector_trchest_3',
        itemName: '新锐谷地探物器',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 100_000,
        discount: 0,
        currentPrice: 100_000,
      },
      // 人文物产
      {
        itemId: 'item_spaceship_exhibits_tundra_2',
        itemName: '弧线2000模型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16_000_000,
        discount: 0,
        currentPrice: 16_000_000,
      },
      {
        itemId: 'item_spaceship_exhibits_tundra_3',
        itemName: '冠军钻探器',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16_000_000,
        discount: 0,
        currentPrice: 16_000_000,
      },
      {
        itemId: 'item_spaceship_exhibits_tundra_4',
        itemName: '生机盆景',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 16_000_000,
        discount: 0,
        currentPrice: 16_000_000,
      },
      {
        itemId: 'item_gift_tundra_1',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_2',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_3',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_4',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_5',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_6',
        itemName: '塞梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_7',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 2,
        originalPrice: 30_000,
        discount: -0.99,
        currentPrice: 300,
      },
      {
        itemId: 'item_gift_tundra_1',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_2',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_3',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_4',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_5',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: '赛梦珂披巾',
        itemName: '赛梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_7',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 30_000,
        discount: -0.8,
        currentPrice: 6000,
      },
      {
        itemId: 'item_gift_tundra_1',
        itemName: '醚质相机',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_gift_tundra_2',
        itemName: '星门锁',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_gift_tundra_3',
        itemName: '冲浪大赛门票',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_gift_tundra_4',
        itemName: '耶尔什微风',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_gift_tundra_5',
        itemName: '浪潮海石',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: '赛梦珂披巾',
        itemName: '赛梦珂披巾',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_gift_tundra_7',
        itemName: '《前沿瞭望》',
        quantityPerGroup: 1,
        stockGroups: 60,
        originalPrice: 30_000,
        discount: 0,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_spaceship_exhibits_tundra_1',
        itemName: '兰姆先生',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 10_000,
        discount: -0.99,
        currentPrice: 100,
      },
    ],
  },
  {
    shopId: '武陵物资调度 − 稳定需求物资',
    shopName: '武陵物资调度 − 稳定需求物资',
    shopItems: [
      // 日用消耗
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.92,
        currentPrice: 4000,
      },
      {
        itemId: 'item_ticketgacha_standard_single',
        itemName: '基础寻访凭证',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 50_000,
        discount: -0.85,
        currentPrice: 7500,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 10_000,
        stockGroups: 10,
        originalPrice: 5000,
        discount: -0.95,
        currentPrice: 500,
      },
      {
        itemId: 'item_gold',
        itemName: '折金票',
        quantityPerGroup: 10_000,
        stockGroups: 10,
        originalPrice: 5000,
        discount: -0.9,
        currentPrice: 1000,
      },
      {
        itemId: 'item_gem_stable_energy_point_wuling',
        itemName: '武陵刻写券',
        quantityPerGroup: 1,
        stockGroups: 15,
        originalPrice: 1_600_000,
        discount: -0.92,
        currentPrice: 128_000,
      },
      {
        itemId: 'item_gem_stable_energy_point_wuling',
        itemName: '武陵刻写券',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 1_600_000,
        discount: -0.85,
        currentPrice: 240_000,
      },
      {
        itemId: 'item_corp3_grass1_1',
        itemName: '正本补元汤剂',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 300_000,
        discount: -0.95,
        currentPrice: 15_000,
      },
      {
        itemId: 'item_corp4_grass2_1',
        itemName: '锦素炒饭',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 300_000,
        discount: -0.95,
        currentPrice: 15_000,
      },
      {
        itemId: 'item_corp3_grass1_1',
        itemName: '正本补元汤剂',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 300_000,
        discount: -0.9,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_corp4_grass2_1',
        itemName: '锦素炒饭',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 300_000,
        discount: -0.9,
        currentPrice: 30_000,
      },
      // 工业货品
      {
        itemId: 'item_equip_enhance_wuling',
        itemName: '武陵精锻助剂',
        quantityPerGroup: 1,
        stockGroups: 40,
        originalPrice: 800_000,
        discount: -0.92,
        currentPrice: 64_000,
      },
      {
        itemId: 'item_equip_enhance_wuling',
        itemName: '武陵精锻助剂',
        quantityPerGroup: 1,
        stockGroups: 20,
        originalPrice: 800_000,
        discount: -0.85,
        currentPrice: 120_000,
      },
      {
        itemId: 'item_wuling_detector_coin_3',
        itemName: '新锐武陵罗盘',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200_000,
        discount: -0.92,
        currentPrice: 16_000,
      },
      {
        itemId: 'item_wuling_detector_trchest_3',
        itemName: '新锐武陵探物器',
        quantityPerGroup: 1,
        stockGroups: 10,
        originalPrice: 200_000,
        discount: -0.92,
        currentPrice: 16_000,
      },
      {
        itemId: 'item_wuling_detector_coin_3',
        itemName: '新锐武陵罗盘',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 200_000,
        discount: -0.85,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_wuling_detector_trchest_3',
        itemName: '新锐武陵探物器',
        quantityPerGroup: 1,
        stockGroups: 5,
        originalPrice: 200_000,
        discount: -0.85,
        currentPrice: 30_000,
      },
      {
        itemId: 'item_equip_t4_suit_attri01_edc_06',
        itemName: '碾骨小雕像·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_fire_natr01_edc_03',
        itemName: '动火用电力匣',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_parts_wuling01_edc_01',
        itemName: '纾难识别牌',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_parts_wuling01_edc_02',
        itemName: '纾难识别牌·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_parts_wuling01_edc_03',
        itemName: '纾难印章',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_parts_wuling01_edc_04',
        itemName: '纾难印章·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_heal01_edc_05',
        itemName: '生物辅助接驳器·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_criti01_edc_05',
        itemName: 'M.I.警用刺刃·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_atk02_edc_04',
        itemName: '50式应龙短刃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_atk02_edc_05',
        itemName: '50式应龙短刃·壹型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_criti01_body_04',
        itemName: 'M.I.警用罩衣·贰型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_criti01_edc_01',
        itemName: 'M.I.警用臂环',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_criti01_edc_02',
        itemName: 'M.I.警用瞄具',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      {
        itemId: 'item_equip_t4_suit_criti01_edc_03',
        itemName: 'M.I.警用工具组',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 5000,
        discount: 0,
        currentPrice: 5000,
      },
      // 人文物产
      {
        itemId: 'item_spaceship_exhibits_jinlong_2',
        itemName: '天师桩模型',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 4_000_000,
        discount: 0,
        currentPrice: 4_000_000,
      },
      {
        itemId: 'item_gift_jinlong_1',
        itemName: '岳研茶盒',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60_000,
        discount: -0.92,
        currentPrice: 4800,
      },
      {
        itemId: 'item_gift_jinlong_2',
        itemName: '应龙哑铃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60_000,
        discount: -0.92,
        currentPrice: 4800,
      },
      {
        itemId: 'item_gift_jinlong_1',
        itemName: '岳研茶盒',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60_000,
        discount: -0.85,
        currentPrice: 9000,
      },
      {
        itemId: 'item_gift_jinlong_2',
        itemName: '应龙哑铃',
        quantityPerGroup: 1,
        stockGroups: 1,
        originalPrice: 60_000,
        discount: -0.85,
        currentPrice: 9000,
      },
    ],
  },
];
